#!/bin/bash

# Perform system upgrade via apt-get
function update {
if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
	# Distro-Sync
	show_info 'Performing system update...'
	sudo dnf clean all
	sudo dnf distro-sync -y --allowerasing
	sudo dnf upgrade --refresh
	sudo dnf system-upgrade download --releasever=NUM
	
	sudo rpm --rebuilddb
	sudo rpmconf -a
	# Done
	show_success 'Done.'
	# Check
	EXITSTATUS=$1
	if [[ $EXITSTATUS != 0 ]]; then
		# Already up-to-date
		show_success 'Already up-to-date.'
		whiptail --title "Finished" --msgbox "System is already up-to-date." 8 78
		main
	else
		whiptail --title "Finished" --msgbox "System update complete" 8 78
		main
	fi
else
	main
fi
}
